version: '3.8'

services:
  student-app:
    image: app/jwt-main:Auth  # Replace with your actual image name from Docker Hub
    ports:
      - "8080:8080"
    environment:
      MONGO_URI: mongodb://mongodb:27017/?retryWrites=true
      DATABASE_NAME: test
    depends_on:
      - mongodb

  mongodb:
    image: mongo:Auth
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongo-data:
